
Type *any_type = NULL;
Type *same_type = NULL;
Type *type_type = NULL;
Type *ovalue_type = NULL;
Type *lvalue_type = NULL;
Type *code_type = NULL;
Type *metatype_type = NULL;
Type *void_type = NULL;
Type *multi_type = NULL;
Type *boolean_type = NULL;
Type *integer_type = NULL;
Type *integer32_type = NULL;
Type *integer16_type = NULL;
Type *integer8_type = NULL;
Type *unsigned_integer_type = NULL;
Type *unsigned_integer32_type = NULL;
Type *unsigned_integer16_type = NULL;
Type *unsigned_integer8_type = NULL;
Type *character_type = NULL;
Type *reference_type = NULL;
Type *borrowed_type = NULL;
Type *role_type = NULL;
Type *array_type = NULL;
Type *enumeration_metatype = NULL;
Type *treenumeration_metatype = NULL;
Type *integer_metatype = NULL;
Type *record_metatype = NULL;
Type *class_metatype = NULL;
Type *interface_metatype = NULL;
Type *implementation_metatype = NULL;
Type *streamifiable_type = NULL;
Type *iterator_type = NULL;

TypeSpec BOGUS_TS;
TypeSpec VOID_TS;
TypeSpec MULTI_TS;
TypeSpec MULTI_LVALUE_TS;
TypeSpec ANY_TS;
TypeSpec ANY_TYPE_TS;
TypeSpec ANY_OVALUE_TS;
TypeSpec ANY_LVALUE_TS;
TypeSpec SAME_TS;
TypeSpec METATYPE_TS;
TypeSpec TREENUMMETA_TS;
TypeSpec BOOLEAN_TS;
TypeSpec INTEGER_TS;
TypeSpec INTEGER_LVALUE_TS;
TypeSpec INTEGER_OVALUE_TS;
TypeSpec BOOLEAN_LVALUE_TS;
TypeSpec UNSIGNED_INTEGER8_TS;
TypeSpec UNSIGNED_INTEGER8_ARRAY_REFERENCE_TS;
TypeSpec CHARACTER_TS;
TypeSpec CHARACTER_LVALUE_TS;
TypeSpec CHARACTER_ARRAY_REFERENCE_TS;
TypeSpec CHARACTER_ARRAY_REFERENCE_LVALUE_TS;
TypeSpec ANY_REFERENCE_TS;
TypeSpec ANY_REFERENCE_LVALUE_TS;
TypeSpec ANY_ARRAY_REFERENCE_TS;
TypeSpec VOID_CODE_TS;
TypeSpec BOOLEAN_CODE_TS;
TypeSpec STREAMIFIABLE_TS;
TypeSpec ANY_ITERATOR_TS;

