
// Builtins

// Vizipok-csodapok!
MetaType *metatype_hypertype = NULL;

MetaType *type_metatype = NULL;

Type *any_type = NULL;
Type *any2_type = NULL;
Type *any3_type = NULL;
Type *anyid_type = NULL;
Type *anyid2_type = NULL;
Type *anyid3_type = NULL;
Type *anytuple_type = NULL;
Type *anytuple2_type = NULL;
Type *anytuple3_type = NULL;
Type *same_type = NULL;
Type *same2_type = NULL;
Type *same3_type = NULL;
Type *sameid_type = NULL;
Type *sameid2_type = NULL;
Type *sameid3_type = NULL;
Type *sametuple_type = NULL;
Type *sametuple2_type = NULL;
Type *sametuple3_type = NULL;

MetaType *value_metatype = NULL;
MetaType *identity_metatype = NULL;
MetaType *module_metatype = NULL;
MetaType *tuple_metatype = NULL;
MetaType *argument_metatype = NULL;
MetaType *enumeration_metatype = NULL;
MetaType *treenumeration_metatype = NULL;
MetaType *integer_metatype = NULL;
MetaType *record_metatype = NULL;
MetaType *union_metatype = NULL;
MetaType *abstract_metatype = NULL;
MetaType *class_metatype = NULL;
MetaType *singleton_metatype = NULL;
MetaType *interface_metatype = NULL;
MetaType *import_metatype = NULL;

Type *ovalue_type = NULL;
Type *lvalue_type = NULL;
Type *dvalue_type = NULL;
Type *code_type = NULL;
Type *void_type = NULL;
Type *unit_type = NULL;
Type *partial_type = NULL;
Type *uninitialized_type = NULL;
Type *initializable_type = NULL;
Type *stringtemplate_type = NULL;
Type *bare_type = NULL;
Type *whatever_type = NULL;
Type *tuple0_type = NULL;
Type *tuple1_type = NULL;
Type *tuple2_type = NULL;
Type *tuple3_type = NULL;

Type *boolean_type = NULL;
Type *integer_type = NULL;
Type *integer32_type = NULL;
Type *integer16_type = NULL;
Type *integer8_type = NULL;
Type *unsigned_integer_type = NULL;
Type *unsigned_integer32_type = NULL;
Type *unsigned_integer16_type = NULL;
Type *unsigned_integer8_type = NULL;
Type *character_type = NULL;
Type *float_type = NULL;
Type *ref_type = NULL;
Type *ptr_type = NULL;
Type *nosyvalue_type = NULL;
Type *nosytree_type = NULL;
Type *nosyref_type = NULL;
Type *weakref_type = NULL;
Type *linearray_type = NULL;
Type *circularray_type = NULL;
Type *rbtree_type = NULL;
Type *string_type = NULL;
Type *slice_type = NULL;
Type *option_type = NULL;
Type *optionis_type = NULL;
Type *optionas_type = NULL;
Type *array_type = NULL;
Type *queue_type = NULL;
Type *set_type = NULL;
Type *map_type = NULL;
Type *weakvaluemap_type = NULL;
Type *weakindexmap_type = NULL;
Type *weakset_type = NULL;
Type *countup_type = NULL;
Type *countdown_type = NULL;
Type *item_type = NULL;
Type *arrayelemiter_type = NULL;
Type *arrayindexiter_type = NULL;
Type *arrayitemiter_type = NULL;
Type *queueelemiter_type = NULL;
Type *queueindexiter_type = NULL;
Type *queueitemiter_type = NULL;
Type *setelembyageiter_type = NULL;
Type *setelembyorderiter_type = NULL;
Type *mapitembyageiter_type = NULL;
Type *mapitembyorderiter_type = NULL;
Type *mapindexbyageiter_type = NULL;
Type *mapindexbyorderiter_type = NULL;
Type *sliceelemiter_type = NULL;
Type *sliceindexiter_type = NULL;
Type *sliceitemiter_type = NULL;

Type *colon_type = NULL;
DataScope *colon_scope = NULL;
Value *colon_value = NULL;

TreenumerationType *iterator_done_exception_type = NULL;
TreenumerationType *container_full_exception_type = NULL;
TreenumerationType *container_empty_exception_type = NULL;
TreenumerationType *container_lent_exception_type = NULL;
TreenumerationType *match_unmatched_exception_type = NULL;
TreenumerationType *lookup_exception_type = NULL;
TreenumerationType *code_break_exception_type = NULL;
TreenumerationType *errno_exception_type = NULL;
TreenumerationType *parse_exception_type = NULL;

InterfaceType *streamifiable_type = NULL;
InterfaceType *iterator_type = NULL;
InterfaceType *iterable_type = NULL;
AbstractType *application_type = NULL;

TypeSpec HYPERTYPE_TS;
TypeSpec NO_TS;
TypeSpec VOID_TS;
TypeSpec ANY_TS;
TypeSpec ANY_OVALUE_TS;
TypeSpec ANY_LVALUE_TS;
TypeSpec SAME_TS;
TypeSpec SAME_LVALUE_TS;
TypeSpec SAME2_LVALUE_TS;
TypeSpec UNIT_TS;
TypeSpec WHATEVER_TS;
TypeSpec WHATEVER_TUPLE1_CODE_TS;
TypeSpec BOOLEAN_TS;
TypeSpec INTEGER_TS;
TypeSpec INTEGER_LVALUE_TS;
TypeSpec INTEGER_OVALUE_TS;
TypeSpec BOOLEAN_LVALUE_TS;
TypeSpec UNSIGNED_INTEGER8_TS;
TypeSpec UNSIGNED_INTEGER8_ARRAY_TS;
TypeSpec UNTEGER_TS;
TypeSpec CHARACTER_TS;
TypeSpec CHARACTER_LVALUE_TS;
TypeSpec CHARACTER_ARRAY_TS;
TypeSpec CHARACTER_ARRAY_LVALUE_TS;
TypeSpec FLOAT_TS;
TypeSpec FLOAT_LVALUE_TS;
TypeSpec ANYID_REF_TS;
TypeSpec ANYID_REF_LVALUE_TS;
TypeSpec ANYID_PTR_TS;
TypeSpec ANYID_PTR_LVALUE_TS;
TypeSpec ANYID_WEAKREF_TS;
TypeSpec ANYID_WEAKREF_LVALUE_TS;
TypeSpec SAMEID_NOSYVALUE_NOSYCONTAINER_REF_LVALUE_TS;
TypeSpec ANY_UNINITIALIZED_TS;
TypeSpec BARE_UNINITIALIZED_TS;
TypeSpec STRINGTEMPLATE_TS;
TypeSpec ANY_ARRAY_TS;
TypeSpec ANY_ARRAY_LVALUE_TS;
TypeSpec SAME_ARRAY_TS;
TypeSpec SAME_LINEARRAY_REF_LVALUE_TS;
TypeSpec ANY_QUEUE_TS;
TypeSpec ANY_QUEUE_LVALUE_TS;
TypeSpec SAME_QUEUE_TS;
TypeSpec SAME_CIRCULARRAY_REF_LVALUE_TS;
TypeSpec ANY_RBTREE_REF_TS;
TypeSpec ANY_RBTREE_REF_LVALUE_TS;
TypeSpec SAME_RBTREE_REF_LVALUE_TS;
TypeSpec ANY_RBTREE_PTR_TS;
TypeSpec SAME_SAME2_ITEM_RBTREE_REF_LVALUE_TS;
TypeSpec TUPLE0_CODE_TS;
TypeSpec BOOLEAN_TUPLE1_CODE_TS;
TypeSpec STRING_TS;
TypeSpec STRING_LVALUE_TS;
TypeSpec STRING_ARRAY_TS;
TypeSpec ANY_SLICE_TS;
TypeSpec BYTE_SLICE_TS;
TypeSpec ANY_OPTION_TS;
TypeSpec ANY_OPTION_LVALUE_TS;
TypeSpec OPTIONSELECTOR_TS;
TypeSpec ANY_ANY2_MAP_TS;
TypeSpec ANY_ANY2_MAP_LVALUE_TS;
TypeSpec ANY_SET_TS;
TypeSpec ANY_SET_LVALUE_TS;
TypeSpec SAME_SET_TS;
TypeSpec SAME_SAME2_MAP_TS;
TypeSpec ANY_ANYID2_WEAKVALUEMAP_TS;
TypeSpec SAME_SAMEID2_NOSYVALUE_ITEM_RBTREE_REF_TS;
TypeSpec SAME_SAMEID2_NOSYVALUE_ITEM_RBTREE_REF_LVALUE_TS;
TypeSpec ANYID_ANY2_WEAKINDEXMAP_TS;
TypeSpec SAMEID_NOSYVALUE_SAME2_ITEM_RBTREE_REF_TS;
TypeSpec SAMEID_NOSYVALUE_SAME2_ITEM_RBTREE_REF_LVALUE_TS;
TypeSpec ANYID_WEAKSET_TS;

TypeSpec SAMEID_NOSYVALUE_LVALUE_TS;

TypeSpec SAMEID_NOSYVALUE_RBTREE_REF_TS;
TypeSpec SAMEID_NOSYVALUE_RBTREE_REF_LVALUE_TS;

TypeSpec SAMEID_NOSYVALUE_TS;
TypeSpec SAMEID_NOSYVALUE_SAME2_ITEM_TS;
TypeSpec SAME_SAMEID2_NOSYVALUE_ITEM_TS;

TypeSpec STREAMIFIABLE_TS;
TypeSpec ANYTUPLE_ITERATOR_TS;
TypeSpec SAMETUPLE_ITERATOR_TS;
TypeSpec SAME_SAME2_TUPLE2_ITERATOR_TS;
TypeSpec ANYTUPLE_ITERABLE_TS;
TypeSpec SAMETUPLE_ITERABLE_TS;
TypeSpec INTEGER_TUPLE1_ITERATOR_TS;
TypeSpec INTEGER_TUPLE1_ITERABLE_TS;
TypeSpec SAME_TUPLE1_TS;
TypeSpec INTEGER_TUPLE1_TS;
TypeSpec SAME_SAME2_TUPLE2_TS;
TypeSpec INTEGER_SAME_TUPLE2_TS;
TypeSpec SAME_TUPLE1_ITERABLE_TS;
TypeSpec SAME_LVALUE_TUPLE1_TS;
TypeSpec INTEGER_SAME_LVALUE_TUPLE2_TS;
TypeSpec SAME_SAME2_LVALUE_TUPLE2_TS;
TypeSpec SAMETUPLE_TS;
TypeSpec COUNTUP_TS;
TypeSpec COUNTDOWN_TS;
TypeSpec SAME_ARRAYELEMITER_TS;
TypeSpec SAME_ARRAYINDEXITER_TS;
TypeSpec SAME_ARRAYITEMITER_TS;
TypeSpec SAME_QUEUEELEMITER_TS;
TypeSpec SAME_QUEUEINDEXITER_TS;
TypeSpec SAME_QUEUEITEMITER_TS;
TypeSpec SAME_SETELEMBYAGEITER_TS;
TypeSpec SAME_SETELEMBYORDERITER_TS;
TypeSpec SAME_SAME2_MAPITEMBYAGEITER_TS;
TypeSpec SAME_SAME2_MAPITEMBYORDERITER_TS;
TypeSpec SAME_SAME2_MAPINDEXBYAGEITER_TS;
TypeSpec SAME_SAME2_MAPINDEXBYORDERITER_TS;
TypeSpec SAME_SLICEELEMITER_TS;
TypeSpec SAME_SLICEINDEXITER_TS;
TypeSpec SAME_SLICEITEMITER_TS;
TypeSpec ANY_ANY2_ITEM_TS;
TypeSpec SAME_SAME2_ITEM_TS;
TypeSpec INTEGER_SAME_ITEM_TS;
TypeSpec COLON_TS;

extern TreenumInput errno_treenum_input[];

RootScope *init_builtins();

