const int HEAP_HEADER_SIZE = 32;
const int HEAP_HEADER_OFFSET = -32;
const int HEAP_REFCOUNT_OFFSET = -32;
const int HEAP_WEAKCOUNT_OFFSET = -24;
const int HEAP_FINALIZER_OFFSET = -16;

const int ARRAY_HEADER_SIZE = 16;
const int ARRAY_RESERVATION_OFFSET = 0;
const int ARRAY_LENGTH_OFFSET = 8;
const int ARRAY_ELEMS_OFFSET = 16;
const int ARRAY_MINIMUM_RESERVATION = 8;

const int CIRCULARRAY_HEADER_SIZE = 32;
const int CIRCULARRAY_RESERVATION_OFFSET = 0;
const int CIRCULARRAY_LENGTH_OFFSET = 8;
const int CIRCULARRAY_FRONT_OFFSET = 16;
const int CIRCULARRAY_ELEMS_OFFSET = 32;
const int CIRCULARRAY_MINIMUM_RESERVATION = 8;

const int CLASS_HEADER_SIZE = 8;
const int CLASS_VT_OFFSET = 0;
const int CLASS_MEMBERS_OFFSET = 8;

const int RBTREE_HEADER_SIZE = 48;
const int RBTREE_RESERVATION_OFFSET = 0;
const int RBTREE_LENGTH_OFFSET = 8;
const int RBTREE_ROOT_OFFSET = 16;
const int RBTREE_FIRST_OFFSET = 24;
const int RBTREE_LAST_OFFSET = 32;
const int RBTREE_VACANT_OFFSET = 40;
const int RBTREE_ELEMS_OFFSET = 48;
const int RBTREE_MINIMUM_RESERVATION = 8;

const int RBNODE_HEADER_SIZE = 32;
const int RBNODE_PREV_IS_RED_OFFSET = 0;
const int RBNODE_NEXT_OFFSET = 8;
const int RBNODE_LEFT_OFFSET = 16;
const int RBNODE_RIGHT_OFFSET = 24;
const int RBNODE_VALUE_OFFSET = 32;
const int RBNODE_NIL = 0;

const int ADDRESS_SIZE = 8;
const int REFERENCE_SIZE = 8;
const int ALIAS_SIZE = 8;
const int INTEGER_SIZE = 8;
const int CHARACTER_SIZE = 2;
