
#include "declaration.h"
#include "scope.h"
#include "util.h"
#include "identifier.h"
#include "allocable.h"
#include "function.h"
#include "associable.h"
#include "type.h"

#include "interface.h"
#include "basic.h"
#include "float.h"
#include "reference.h"
#include "record.h"
#include "class.h"
#include "option.h"
#include "container.h"
#include "nosy.h"


#include "declaration.cpp"
#include "scope.cpp"
#include "util.cpp"
#include "identifier.cpp"
#include "allocable.cpp"
#include "function.cpp"
#include "associable.cpp"
#include "type.cpp"

#include "interface.cpp"
#include "basic.cpp"
#include "float.cpp"
#include "reference.cpp"
#include "record.cpp"
#include "class.cpp"
#include "option.cpp"
#include "container.cpp"
#include "nosy.cpp"
