
#include "declaration.cpp"
#include "scope.cpp"
#include "identifier.cpp"
#include "allocable.cpp"
#include "function.cpp"
#include "type.cpp"
#include "metatype.cpp"

#include "interface.cpp"
#include "basic.cpp"
#include "float.cpp"
#include "reference.cpp"
#include "record.cpp"
#include "class.cpp"
#include "option.cpp"
#include "singleton.cpp"
#include "container.cpp"
